# Generated by Django 5.2.8 on 2025-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('catergorya', models.CharField(max_length=120)),
                ('create_at', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
